//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated with NenTools.ImGui.Generator for ImGui Version "1.92.5"
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Numerics;

namespace NenTools.ImGui.Native;

public unsafe partial class ImGuiMethods
{
    [DllImport("ImGui/Binaries/ImGuiLib", CallingConvention = CallingConvention.Cdecl, EntryPoint = "ImGui_LoadIniSettingsFromMemory", ExactSpelling = true)]
    public static extern void LoadIniSettingsFromMemory(byte* ini_data, nuint ini_size);

    [DllImport("ImGui/Binaries/ImGuiLib", CallingConvention = CallingConvention.Cdecl, EntryPoint = "ImGui_SaveIniSettingsToMemory", ExactSpelling = true)]
    [return: MarshalAs(UnmanagedType.LPUTF8Str)]
    public static extern string SaveIniSettingsToMemory(nuint out_ini_size);

    // We have these so that we can pass null to p_open.
    [DllImport("ImGui/Binaries/ImGuiLib", CallingConvention = CallingConvention.Cdecl, EntryPoint = "ImGui_Begin", ExactSpelling = true)]
    public static extern bool Begin([MarshalAs(UnmanagedType.LPUTF8Str)] string name, bool* p_open, int flags);
    [DllImport("ImGui/Binaries/ImGuiLib", CallingConvention = CallingConvention.Cdecl, EntryPoint = "ImGui_Begin", ExactSpelling = true)]
    public static extern bool Begin(sbyte* name, bool* p_open, int flags);
}